// technical-questions-repo/technical-questions-app/constants/topics.ts
export const TECHNICAL_TOPICS = [
  "Custom Topic",
  "AWS",
  "Operating Systems",
  "Python",
  "Java",
  "JavaScript",
  "Data Structures",
  "Algorithms",
  "Databases",
  "Networking",
  "System Design",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Machine Learning",
  "Artificial Intelligence",
  "Web Development (Frontend)",
  "Web Development (Backend)",
  "Mobile Development",
  "Software Testing",
  "Version Control (Git)",
];

export const DATABASES = [
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Cassandra",
  "Elasticsearch",
  "SQLite",
  "Oracle",
  "Microsoft SQL Server",
  "DynamoDB",
];
