-- ============================================
--  FULL TECHNICAL_QUESTIONS TABLE SCHEMA
-- ============================================

CREATE TABLE public.technical_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Core question fields
    question_text TEXT,
    question_type TEXT NOT NULL CHECK (
        question_type IN ('mcq', 'short_answer', 'long_answer')
    ),
    tech_stack TEXT,
    difficulty TEXT NOT NULL CHECK (
        difficulty IN ('Easy', 'Medium', 'Hard')
    ),
    topic TEXT,

    -- MCQ option fields
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_answer TEXT,


    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- INDEXES (From original DB dump + useful ones)
-- ============================================

-- Index by difficulty
CREATE INDEX idx_questions_difficulty
ON public.technical_questions (difficulty);

-- Index by tech_stack
CREATE INDEX idx_questions_tech_stack
ON public.technical_questions (tech_stack);

-- Index by question_type
CREATE INDEX idx_questions_type
ON public.technical_questions (question_type);

-- Useful index for filtering by topic + difficulty
CREATE INDEX idx_questions_topic
ON public.technical_questions (topic);


-- ============================================
-- UPDATED_AT AUTO-UPDATE TRIGGER
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_updated_at
BEFORE UPDATE ON public.technical_questions
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
